-- ============================================================================
-- Bronze Layer: Raw staging tables (1:1 mapping from source CSVs/files)
-- ============================================================================

-- Source: customer-data-27-09-2024.csv
CREATE TABLE IF NOT EXISTS bronze.raw_customer_data (
    address             TEXT,
    created_at          TIMESTAMPTZ,
    last_updated_by     TEXT,
    last_updated_in_store TEXT,
    last_updated_on     TIMESTAMPTZ,
    mobile              TEXT,
    name                TEXT,
    pincode             TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: Location_Master_02102024.csv
CREATE TABLE IF NOT EXISTS bronze.raw_location_master (
    store_code          TEXT,
    store_name          TEXT,
    store_format        TEXT,
    store_zone          TEXT,
    store_business_region TEXT,
    store_region_code   TEXT,
    store_state         TEXT,
    store_city_code     TEXT,
    store_city_description TEXT,
    store_pincode       TEXT,
    store_address       TEXT,
    status              TEXT,
    store_opening_date  TEXT,
    store_closing_date  TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: ZABM_Full_AV1_20241002_050105.csv (Article/Product Master - pipe delimited)
CREATE TABLE IF NOT EXISTS bronze.raw_article_master (
    article             TEXT,
    article_description TEXT,
    segment_code        TEXT,
    segment_desc        TEXT,
    family_code         TEXT,
    family_desc         TEXT,
    class_code          TEXT,
    class_desc          TEXT,
    brick_code          TEXT,
    brick_desc          TEXT,
    manufacturer_code   TEXT,
    manufacturer_desc   TEXT,
    brand_code          TEXT,
    brand_desc          TEXT,
    category_code       TEXT,
    category_desc       TEXT,
    subcategory_code    TEXT,
    subcategory_desc    TEXT,
    created_on          TEXT,
    last_change         TEXT,
    created_by          TEXT,
    clt                 TEXT,
    article_type        TEXT,
    old_article_no      TEXT,
    base_uom            TEXT,
    lab_off             TEXT,
    valid_from          TEXT,
    ean_upc             TEXT,
    ct                  TEXT,
    document            TEXT,
    pgr                 TEXT,
    temp                TEXT,
    net_weight          TEXT,
    weight_uom          TEXT,
    status              TEXT,
    group_code          TEXT,
    disposal_status     TEXT,
    listing             TEXT,
    article_category    TEXT,
    length              TEXT,
    length_uom          TEXT,
    width               TEXT,
    width_uom           TEXT,
    height              TEXT,
    height_uom          TEXT,
    shelf_life          TEXT,
    remaining_shelf_life TEXT,
    tagging             TEXT,
    season              TEXT,
    season_year         TEXT,
    hsn_code            TEXT,
    nbl_sku_code        TEXT,
    tgs                 TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: ecom_category_20240307050330.csv
CREATE TABLE IF NOT EXISTS bronze.raw_ecom_category (
    id                  TEXT,
    category_name       TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: ecom_productmaster_20240307050330.csv
CREATE TABLE IF NOT EXISTS bronze.raw_ecom_product_master (
    sku                 TEXT,
    name                TEXT,
    product_type        TEXT,
    visibility          TEXT,
    category            TEXT,
    sub_category        TEXT,
    sub_sub_category    TEXT,
    store_code          TEXT,
    quantity            TEXT,
    unit                TEXT,
    brand               TEXT,
    food_type           TEXT,
    capacity            TEXT,
    package_type        TEXT,
    config_type         TEXT,
    country_of_origin   TEXT,
    deep_url            TEXT,
    is_liquor           TEXT,
    status              TEXT,
    created_at          TEXT,
    updated             TEXT,
    style_code          TEXT,
    color               TEXT,
    size                TEXT,
    gender              TEXT,
    material            TEXT,
    occasion            TEXT,
    category2           TEXT,
    shape_fit           TEXT,
    weave_type          TEXT,
    festival_product    TEXT,
    sole                TEXT,
    lining              TEXT,
    pocket              TEXT,
    sleeve_type         TEXT,
    heel_type           TEXT,
    toe_shape           TEXT,
    neck_type           TEXT,
    fabric_type         TEXT,
    fabric              TEXT,
    sleeve_style        TEXT,
    heel_height         TEXT,
    dress_type          TEXT,
    is_active           TEXT,
    description         TEXT,
    level               TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: NPS May_24.csv
CREATE TABLE IF NOT EXISTS bronze.raw_nps_survey (
    mobile              TEXT,
    store_code          TEXT,
    bill_date           TEXT,
    cleanliness_hygiene INT,
    product_availability INT,
    quality_freshness   INT,
    value_for_money     INT,
    promotional_offers  INT,
    staff_assistance    INT,
    checkout_experience INT,
    overall_rating      INT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: Promo_SRL_02102024.csv
CREATE TABLE IF NOT EXISTS bronze.raw_promotions (
    promotion_id        TEXT,
    deal_code           TEXT,
    discount_type       TEXT,
    fill_date           TEXT,
    valid_from          TEXT,
    valid_to            TEXT,
    r_no                TEXT,
    item_no             TEXT,
    sl_no               TEXT,
    article             TEXT,
    description         TEXT,
    uom                 TEXT,
    brand               TEXT,
    manufacturer        TEXT,
    brick_from          TEXT,
    brick_to            TEXT,
    communication       TEXT,
    offer_text          TEXT,
    sp_price            TEXT,
    percent_off         TEXT,
    rs_off              TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: SRL-PromoCashback20241001233002.csv
CREATE TABLE IF NOT EXISTS bronze.raw_promo_cashback (
    mobile_number       TEXT,
    promo_id            TEXT,
    start_date          TEXT,
    end_date            TEXT,
    create_date         TEXT,
    channel             TEXT,
    amount              TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: FESTIVAL LIST_Updated.xlsx
CREATE TABLE IF NOT EXISTS bronze.raw_festival_list (
    year                TEXT,
    campaign_name       TEXT,
    start_date          TEXT,
    end_date            TEXT,
    geography           TEXT,
    start_day_of_week   TEXT,
    end_day_of_week     TEXT,
    business_region     TEXT,
    zone                TEXT,
    brand               TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: YVM June_24.xlsb (Your Voice Matters - Customer feedback/complaints)
CREATE TABLE IF NOT EXISTS bronze.raw_yvm_feedback (
    sl_no               INT,
    created_by          TEXT,
    store_city          TEXT,
    store_name          TEXT,
    store_code          TEXT,
    region              TEXT,
    mode_of_yvm         TEXT,
    reference_no        TEXT,
    cli_no              TEXT,
    pincode             TEXT,
    staff_behaviour     TEXT,
    store_cleanliness   TEXT,
    billing_efficiency  TEXT,
    product_quality     TEXT,
    products_availability TEXT,
    overall_satisfaction TEXT,
    feedback_text       TEXT,
    toll_free_notes     TEXT,
    salutation          TEXT,
    customer_name       TEXT,
    mobile_no           TEXT,
    landline_no         TEXT,
    email_id            TEXT,
    bill_date1          TEXT,
    bill_no1            TEXT,
    bill_amount1        TEXT,
    till_no1            TEXT,
    order_no1           TEXT,
    feedback_type       TEXT,
    feedback_class      TEXT,
    feedback_sub_class  TEXT,
    primary_tat         TEXT,
    categorized_by      TEXT,
    segment             TEXT,
    family              TEXT,
    class               TEXT,
    product_type        TEXT,
    brand_name          TEXT,
    item_description    TEXT,
    quantity            TEXT,
    resolution          TEXT,
    resolution_notes    TEXT,
    platform_type       TEXT,
    registration_datetime TEXT,
    _loaded_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Source: BILL_DELTA CSV (transaction-level POS data, 2026-01-29 to 2026-02-06)
CREATE TABLE IF NOT EXISTS bronze.raw_bill_delta (
    bill_date               TEXT,
    plant                   TEXT,
    plant_desc              TEXT,
    till_no                 TEXT,
    bill_no                 TEXT,
    line_item_no            TEXT,
    condition_type          TEXT,
    promo_indicator         TEXT,
    city                    TEXT,
    city_desc               TEXT,
    store_format            TEXT,
    region                  TEXT,
    region_desc             TEXT,
    manual_bill_date        TEXT,
    cal_year_month          TEXT,
    calendar_year           TEXT,
    calendar_year_week      TEXT,
    bill_start_time         TEXT,
    bill_end_time           TEXT,
    cashier_no              TEXT,
    cashier_name            TEXT,
    gstin                   TEXT,
    deliv_slot              TEXT,
    deliv_challan_gen       TEXT,
    portal_order_no         TEXT,
    order_date_time         TEXT,
    manual_bill_no          TEXT,
    article                 TEXT,
    article_desc            TEXT,
    segment                 TEXT,
    segment_desc            TEXT,
    family                  TEXT,
    family_desc             TEXT,
    class                   TEXT,
    class_desc              TEXT,
    brick                   TEXT,
    brick_desc              TEXT,
    manufacturer            TEXT,
    manufacturer_name       TEXT,
    brand                   TEXT,
    brand_name              TEXT,
    base_unit               TEXT,
    base_unit_desc          TEXT,
    gift_item_indicator     TEXT,
    indicator_for_bill      TEXT,
    sales_return            TEXT,
    line_item_count         TEXT,
    liquidity_type          TEXT,
    mobile_number           TEXT,
    otp_feed_time           TEXT,
    otp_gen_time            TEXT,
    card_number_1           TEXT,
    card_number_2           TEXT,
    card_number_3           TEXT,
    card_number_4           TEXT,
    card_number_5           TEXT,
    card_number_6           TEXT,
    card_number_7           TEXT,
    card_number_8           TEXT,
    vka0_discount_value     TEXT,
    ka04_discount_value     TEXT,
    ka02_discount_value     TEXT,
    z006_discount_value     TEXT,
    z007_discount_value     TEXT,
    zpro_discount_value     TEXT,
    zfre_discount_value     TEXT,
    zcat_discount_value     TEXT,
    zemp_discount_value     TEXT,
    zbil_discount_value     TEXT,
    total_manual_bill_disc  TEXT,
    queue_length            TEXT,
    billed_mrp              TEXT,
    billed_qty              TEXT,
    total_mrp_value         TEXT,
    gross_sale_value        TEXT,
    total_discount          TEXT,
    _loaded_at              TIMESTAMPTZ DEFAULT NOW(),
    _source_file            TEXT
);

-- Source: CIH Parquet files (20M customer golden records)
CREATE TABLE IF NOT EXISTS bronze.raw_cih_profiles (
    brand_id                    TEXT,
    r1                          TEXT,
    name                        TEXT,
    city                        TEXT,
    created_at                  TEXT,
    customer_group              TEXT,
    device_history              TEXT,
    dob                         TEXT,
    dob_day                     TEXT,
    dob_month                   TEXT,
    dob_year                    TEXT,
    email_domain                TEXT,
    last_device                 TEXT,
    occupation                  TEXT,
    pincode                     TEXT,
    status                      TEXT,
    store_code                  TEXT,
    street                      TEXT,
    region                      TEXT,
    employee                    TEXT,
    pd_preferred_store          TEXT,
    pd_subscription_end_date    TEXT,
    whatsapp                    TEXT,
    age                         TEXT,
    dnd                         TEXT,
    pd_subscription_renewal_count TEXT,
    alternate_street_1          TEXT,
    alternate_street_2          TEXT,
    alternate_street_3          TEXT,
    alternate_street_4          TEXT,
    alternate_street_5          TEXT,
    alternate_city_1            TEXT,
    alternate_city_2            TEXT,
    alternate_city_3            TEXT,
    alternate_city_4            TEXT,
    alternate_city_5            TEXT,
    alternate_region_1          TEXT,
    alternate_region_2          TEXT,
    alternate_region_3          TEXT,
    alternate_region_4          TEXT,
    alternate_region_5          TEXT,
    alternate_pincode_1         TEXT,
    alternate_pincode_2         TEXT,
    alternate_pincode_3         TEXT,
    alternate_pincode_4         TEXT,
    alternate_pincode_5         TEXT,
    first_name                  TEXT,
    last_name                   TEXT,
    pd_store_contact_1          TEXT,
    pd_store_contact_2          TEXT,
    gw_customer_flag            TEXT,
    accepts_email_marketing     TEXT,
    accepts_sms_marketing       TEXT,
    total_orders                TEXT,
    total_spent                 TEXT,
    company                     TEXT,
    country                     TEXT,
    email_id                    TEXT,
    customer_surrogate_id       TEXT,
    _loaded_at                  TIMESTAMPTZ DEFAULT NOW(),
    _source_file                TEXT
);
